name: Release

#on:
  #push:
    #branches:
      #- main
      #- track/0

# TODO: remove below and uncomment the block above
on:
  pull_request:
    branches:
      - main


jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@feature/v1
    secrets: inherit
