name: Release

on:
  push:
    branches:
      - main
      - track/3.0

permissions:
  contents: write
  actions: read
  security-events: write

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@feat/self-hosted-runners
    secrets: inherit
    with:
      pack-using-self-hosted-runners: true
