name: Release

on:
  push:
    branches:
      - main
      - track/3.0

permissions:
  # Required for CodeQL security scanning
  security-events: write
  # Required for private repositories
  actions: read
  contents: read

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@feat/tf-tagging
    secrets: inherit
