name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  pull_request:
  # Only use manual trigger for testing
  # schedule:
  #   - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  update-libs:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@feature/v1
    secrets: inherit

